const MODULE_NAME = "subjects";
const ADD_SUBJECT = "ADD_SUBJECT";
const DEL_SUBJECT = "DEL_SUBJECT";
const LISTING_START = "LISTING_START";
const LISTING_END = "LISTING_END";
const CLEAR_SUBJECTS = "CLEAR_SUBJECTS";

export default {
  MODULE_NAME,
  ADD_SUBJECT,
  DEL_SUBJECT,
  LISTING_START,
  LISTING_END,
  CLEAR_SUBJECTS,
};
